### ISSUE TITLE
automatic add user to nosy list if not exist in bpo after PR submitted

### ISSUE THREAD

**Issue by aldwinaldwin** [python/core-workflow#341] opened 2019-07-11 04:01 UTC
User is not in nosy list on bugs.python.org after submitting a PR. User has to add himself to nosy list manually. This for small documentation fixes, a PR is made very quickly and user forgets to added self to the nosy list.

**Comment by Mariatta** [comment] 2019-07-11 05:31
Thank you, I agree it is a great idea. This needs to be done in bpo.

Duplicate of https://github.com/python/bedevere/issues/98
Duplicate of https://github.com/python/bugs.python.org/issues/8

**Comment by Mariatta** [comment] 2019-07-11 05:31
Duplicate of python/bedevere#98

**Comment by Mariatta** [comment] 2019-07-11 05:31
Duplicate of python/bugs.python.org#8

**Comment by aldwinaldwin** [comment] 2019-07-11 06:02
Thank you. I checked the bedevere issues but not the Closed ones. :)

**Closed** 2019-07-19 15:51 UTC
