### ISSUE TITLE
cherry_picker exits with exception when in git worktree dir

### ISSUE THREAD

**Issue by zhangyangyu** [python/core-workflow#217] opened 2018-01-31 13:10 UTC
I use cherry_picker in a git worktree directory, so it means you are not able to checkout master branch. So cherry_picker fails with the exception:

```
 🍒 ⛏
To github.com:zhangyangyu/cpython.git
 * [new branch]            backport-2c7fd46-3.6 -> backport-2c7fd46-3.6

Backport PR URL:
https://github.com/python/cpython/compare/3.6...zhangyangyu:backport-2c7fd46-3.6?expand=1
Traceback (most recent call last):
  File "/usr/local/bin/cherry_picker", line 11, in <module>
    sys.exit(cherry_pick_cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cherry_picker/cherry_picker.py", line 355, in cherry_pick_cli
    cherry_picker.continue_cherry_pick()
  File "/usr/local/lib/python3.6/site-packages/cherry_picker/cherry_picker.py", line 307, in continue_cherry_pick
    self.cleanup_branch(cherry_pick_branch)
  File "/usr/local/lib/python3.6/site-packages/cherry_picker/cherry_picker.py", line 225, in cleanup_branch
    self.checkout_master()
  File "/usr/local/lib/python3.6/site-packages/cherry_picker/cherry_picker.py", line 110, in checkout_master
    self.run_cmd(cmd)
  File "/usr/local/lib/python3.6/site-packages/cherry_picker/cherry_picker.py", line 82, in run_cmd
    output = subprocess.check_output(cmd.split(), stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'checkout', 'master']' returned non-zero exit status 128.
```

Maybe we could remember the branch we are in before using cherry_picker and restore to that branch instead of always master?

**Comment by Mariatta** [comment] 2018-01-31 14:52
Thanks, I think this is duplicate of #132, so I'll close it.
To fully solve the problem, we'll need to implement what's proposed in #107: remembering the state of what was checked out, what the pr remote was, and storing it in some config file.


Duplicate #132

**Comment by Mariatta** [comment] 2018-01-31 14:52
Duplicate #132

**Closed by Mariatta** 2018-01-31 14:52 UTC
Labels: cherry_picker.py

**Comment by zhangyangyu** [comment] 2018-01-31 15:02
Oops, sorry.

**Comment by Mariatta** [comment] 2018-01-31 15:03
No worries :)

**Comment by terryjreedy** [comment] 2018-01-31 18:56
Since I have only been backporting to 3.6, I change 'master' to '3.6 in `checkout_master`.  Since Miss Islinton, I have seldom used the local cherry-picker.  Since I will be backporting to both 3.7 and 3.6 for a while, I hope that continues.
