### ISSUE TITLE
Add bpo link to mention-bot when issue id provide

### ISSUE THREAD

**Issue by lulouie** [python/core-workflow#74] opened 2017-04-25 04:07 UTC
Thought typing bpo link isn't hard.

But it still has some convenience if mention-bot can also provide bpo link when mentioning.

**Comment by brettcannon** [comment] 2017-04-26 17:39
Thanks for the report, @lulouie , but this is a duplicate of python/bedevere#3.

**Closed by brettcannon** 2017-04-26 17:39 UTC
Labels: duplicate
