### ISSUE TITLE
cherry_picker needs Python 3.6

### ISSUE THREAD

**Issue by pitrou** [python/core-workflow#63] opened 2017-03-24 13:02 UTC
It would be nice if at least cherry_picker allowed older Python 3s.
```
$ python -V
Python 3.5.2
$ python -m cherry_picker 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 144, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/antoine/cpython/core-workflow/cherry_picker/cherry_picker.py", line 24
    run_cmd(f"git fetch {upstream}", dry_run=dry_run)
                                  ^
SyntaxError: invalid syntax
```

**Comment by serhiy-storchaka** [comment] 2017-03-24 13:41
This is a duplicate of #56.

**Closed** 2017-03-24 17:21 UTC
Labels: cherry_picker.py, duplicate
